//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name Name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddCourses", ReplyAction="*")]
        WindowsFormsApp2.ServiceReference1.AddCoursesResponse AddCourses(WindowsFormsApp2.ServiceReference1.AddCoursesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddCourses", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp2.ServiceReference1.AddCoursesResponse> AddCoursesAsync(WindowsFormsApp2.ServiceReference1.AddCoursesRequest request);
        
        // CODEGEN: Generating message contract since element name ViewcourseResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Viewcourse", ReplyAction="*")]
        WindowsFormsApp2.ServiceReference1.ViewcourseResponse Viewcourse(WindowsFormsApp2.ServiceReference1.ViewcourseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Viewcourse", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp2.ServiceReference1.ViewcourseResponse> ViewcourseAsync(WindowsFormsApp2.ServiceReference1.ViewcourseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteCourse", ReplyAction="*")]
        void DeleteCourse(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteCourse", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteCourseAsync(int id);
        
        // CODEGEN: Generating message contract since element name Name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditCourse", ReplyAction="*")]
        WindowsFormsApp2.ServiceReference1.EditCourseResponse EditCourse(WindowsFormsApp2.ServiceReference1.EditCourseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditCourse", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp2.ServiceReference1.EditCourseResponse> EditCourseAsync(WindowsFormsApp2.ServiceReference1.EditCourseRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddCoursesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddCourses", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp2.ServiceReference1.AddCoursesRequestBody Body;
        
        public AddCoursesRequest() {
        }
        
        public AddCoursesRequest(WindowsFormsApp2.ServiceReference1.AddCoursesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddCoursesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Description;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int price;
        
        public AddCoursesRequestBody() {
        }
        
        public AddCoursesRequestBody(string Name, string Description, int price) {
            this.Name = Name;
            this.Description = Description;
            this.price = price;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddCoursesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddCoursesResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp2.ServiceReference1.AddCoursesResponseBody Body;
        
        public AddCoursesResponse() {
        }
        
        public AddCoursesResponse(WindowsFormsApp2.ServiceReference1.AddCoursesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddCoursesResponseBody {
        
        public AddCoursesResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ViewcourseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Viewcourse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp2.ServiceReference1.ViewcourseRequestBody Body;
        
        public ViewcourseRequest() {
        }
        
        public ViewcourseRequest(WindowsFormsApp2.ServiceReference1.ViewcourseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ViewcourseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public ViewcourseRequestBody() {
        }
        
        public ViewcourseRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ViewcourseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ViewcourseResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp2.ServiceReference1.ViewcourseResponseBody Body;
        
        public ViewcourseResponse() {
        }
        
        public ViewcourseResponse(WindowsFormsApp2.ServiceReference1.ViewcourseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ViewcourseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApp2.ServiceReference1.ArrayOfString ViewcourseResult;
        
        public ViewcourseResponseBody() {
        }
        
        public ViewcourseResponseBody(WindowsFormsApp2.ServiceReference1.ArrayOfString ViewcourseResult) {
            this.ViewcourseResult = ViewcourseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditCourseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditCourse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp2.ServiceReference1.EditCourseRequestBody Body;
        
        public EditCourseRequest() {
        }
        
        public EditCourseRequest(WindowsFormsApp2.ServiceReference1.EditCourseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditCourseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Description;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int price;
        
        public EditCourseRequestBody() {
        }
        
        public EditCourseRequestBody(int id, string Name, string Description, int price) {
            this.id = id;
            this.Name = Name;
            this.Description = Description;
            this.price = price;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditCourseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditCourseResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp2.ServiceReference1.EditCourseResponseBody Body;
        
        public EditCourseResponse() {
        }
        
        public EditCourseResponse(WindowsFormsApp2.ServiceReference1.EditCourseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class EditCourseResponseBody {
        
        public EditCourseResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WindowsFormsApp2.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WindowsFormsApp2.ServiceReference1.WebService1Soap>, WindowsFormsApp2.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp2.ServiceReference1.AddCoursesResponse WindowsFormsApp2.ServiceReference1.WebService1Soap.AddCourses(WindowsFormsApp2.ServiceReference1.AddCoursesRequest request) {
            return base.Channel.AddCourses(request);
        }
        
        public void AddCourses(string Name, string Description, int price) {
            WindowsFormsApp2.ServiceReference1.AddCoursesRequest inValue = new WindowsFormsApp2.ServiceReference1.AddCoursesRequest();
            inValue.Body = new WindowsFormsApp2.ServiceReference1.AddCoursesRequestBody();
            inValue.Body.Name = Name;
            inValue.Body.Description = Description;
            inValue.Body.price = price;
            WindowsFormsApp2.ServiceReference1.AddCoursesResponse retVal = ((WindowsFormsApp2.ServiceReference1.WebService1Soap)(this)).AddCourses(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp2.ServiceReference1.AddCoursesResponse> WindowsFormsApp2.ServiceReference1.WebService1Soap.AddCoursesAsync(WindowsFormsApp2.ServiceReference1.AddCoursesRequest request) {
            return base.Channel.AddCoursesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp2.ServiceReference1.AddCoursesResponse> AddCoursesAsync(string Name, string Description, int price) {
            WindowsFormsApp2.ServiceReference1.AddCoursesRequest inValue = new WindowsFormsApp2.ServiceReference1.AddCoursesRequest();
            inValue.Body = new WindowsFormsApp2.ServiceReference1.AddCoursesRequestBody();
            inValue.Body.Name = Name;
            inValue.Body.Description = Description;
            inValue.Body.price = price;
            return ((WindowsFormsApp2.ServiceReference1.WebService1Soap)(this)).AddCoursesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp2.ServiceReference1.ViewcourseResponse WindowsFormsApp2.ServiceReference1.WebService1Soap.Viewcourse(WindowsFormsApp2.ServiceReference1.ViewcourseRequest request) {
            return base.Channel.Viewcourse(request);
        }
        
        public WindowsFormsApp2.ServiceReference1.ArrayOfString Viewcourse(int id) {
            WindowsFormsApp2.ServiceReference1.ViewcourseRequest inValue = new WindowsFormsApp2.ServiceReference1.ViewcourseRequest();
            inValue.Body = new WindowsFormsApp2.ServiceReference1.ViewcourseRequestBody();
            inValue.Body.id = id;
            WindowsFormsApp2.ServiceReference1.ViewcourseResponse retVal = ((WindowsFormsApp2.ServiceReference1.WebService1Soap)(this)).Viewcourse(inValue);
            return retVal.Body.ViewcourseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp2.ServiceReference1.ViewcourseResponse> WindowsFormsApp2.ServiceReference1.WebService1Soap.ViewcourseAsync(WindowsFormsApp2.ServiceReference1.ViewcourseRequest request) {
            return base.Channel.ViewcourseAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp2.ServiceReference1.ViewcourseResponse> ViewcourseAsync(int id) {
            WindowsFormsApp2.ServiceReference1.ViewcourseRequest inValue = new WindowsFormsApp2.ServiceReference1.ViewcourseRequest();
            inValue.Body = new WindowsFormsApp2.ServiceReference1.ViewcourseRequestBody();
            inValue.Body.id = id;
            return ((WindowsFormsApp2.ServiceReference1.WebService1Soap)(this)).ViewcourseAsync(inValue);
        }
        
        public void DeleteCourse(int id) {
            base.Channel.DeleteCourse(id);
        }
        
        public System.Threading.Tasks.Task DeleteCourseAsync(int id) {
            return base.Channel.DeleteCourseAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp2.ServiceReference1.EditCourseResponse WindowsFormsApp2.ServiceReference1.WebService1Soap.EditCourse(WindowsFormsApp2.ServiceReference1.EditCourseRequest request) {
            return base.Channel.EditCourse(request);
        }
        
        public void EditCourse(int id, string Name, string Description, int price) {
            WindowsFormsApp2.ServiceReference1.EditCourseRequest inValue = new WindowsFormsApp2.ServiceReference1.EditCourseRequest();
            inValue.Body = new WindowsFormsApp2.ServiceReference1.EditCourseRequestBody();
            inValue.Body.id = id;
            inValue.Body.Name = Name;
            inValue.Body.Description = Description;
            inValue.Body.price = price;
            WindowsFormsApp2.ServiceReference1.EditCourseResponse retVal = ((WindowsFormsApp2.ServiceReference1.WebService1Soap)(this)).EditCourse(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp2.ServiceReference1.EditCourseResponse> WindowsFormsApp2.ServiceReference1.WebService1Soap.EditCourseAsync(WindowsFormsApp2.ServiceReference1.EditCourseRequest request) {
            return base.Channel.EditCourseAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp2.ServiceReference1.EditCourseResponse> EditCourseAsync(int id, string Name, string Description, int price) {
            WindowsFormsApp2.ServiceReference1.EditCourseRequest inValue = new WindowsFormsApp2.ServiceReference1.EditCourseRequest();
            inValue.Body = new WindowsFormsApp2.ServiceReference1.EditCourseRequestBody();
            inValue.Body.id = id;
            inValue.Body.Name = Name;
            inValue.Body.Description = Description;
            inValue.Body.price = price;
            return ((WindowsFormsApp2.ServiceReference1.WebService1Soap)(this)).EditCourseAsync(inValue);
        }
    }
}
