//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2.userServicesReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserData", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UserData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="userServicesReference.usersServicesSoap")]
    public interface usersServicesSoap {
        
        // CODEGEN: Generating message contract since element name user from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertUser", ReplyAction="*")]
        WindowsFormsApp2.userServicesReference.insertUserResponse insertUser(WindowsFormsApp2.userServicesReference.insertUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertUser", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp2.userServicesReference.insertUserResponse> insertUserAsync(WindowsFormsApp2.userServicesReference.insertUserRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserByUsername", ReplyAction="*")]
        WindowsFormsApp2.userServicesReference.GetUserByUsernameResponse GetUserByUsername(WindowsFormsApp2.userServicesReference.GetUserByUsernameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserByUsername", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp2.userServicesReference.GetUserByUsernameResponse> GetUserByUsernameAsync(WindowsFormsApp2.userServicesReference.GetUserByUsernameRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertUser", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp2.userServicesReference.insertUserRequestBody Body;
        
        public insertUserRequest() {
        }
        
        public insertUserRequest(WindowsFormsApp2.userServicesReference.insertUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApp2.userServicesReference.UserData user;
        
        public insertUserRequestBody() {
        }
        
        public insertUserRequestBody(WindowsFormsApp2.userServicesReference.UserData user) {
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp2.userServicesReference.insertUserResponseBody Body;
        
        public insertUserResponse() {
        }
        
        public insertUserResponse(WindowsFormsApp2.userServicesReference.insertUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class insertUserResponseBody {
        
        public insertUserResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserByUsernameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserByUsername", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp2.userServicesReference.GetUserByUsernameRequestBody Body;
        
        public GetUserByUsernameRequest() {
        }
        
        public GetUserByUsernameRequest(WindowsFormsApp2.userServicesReference.GetUserByUsernameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserByUsernameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        public GetUserByUsernameRequestBody() {
        }
        
        public GetUserByUsernameRequestBody(string username) {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserByUsernameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserByUsernameResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp2.userServicesReference.GetUserByUsernameResponseBody Body;
        
        public GetUserByUsernameResponse() {
        }
        
        public GetUserByUsernameResponse(WindowsFormsApp2.userServicesReference.GetUserByUsernameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserByUsernameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApp2.userServicesReference.UserData GetUserByUsernameResult;
        
        public GetUserByUsernameResponseBody() {
        }
        
        public GetUserByUsernameResponseBody(WindowsFormsApp2.userServicesReference.UserData GetUserByUsernameResult) {
            this.GetUserByUsernameResult = GetUserByUsernameResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface usersServicesSoapChannel : WindowsFormsApp2.userServicesReference.usersServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class usersServicesSoapClient : System.ServiceModel.ClientBase<WindowsFormsApp2.userServicesReference.usersServicesSoap>, WindowsFormsApp2.userServicesReference.usersServicesSoap {
        
        public usersServicesSoapClient() {
        }
        
        public usersServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public usersServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public usersServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public usersServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp2.userServicesReference.insertUserResponse WindowsFormsApp2.userServicesReference.usersServicesSoap.insertUser(WindowsFormsApp2.userServicesReference.insertUserRequest request) {
            return base.Channel.insertUser(request);
        }
        
        public void insertUser(WindowsFormsApp2.userServicesReference.UserData user) {
            WindowsFormsApp2.userServicesReference.insertUserRequest inValue = new WindowsFormsApp2.userServicesReference.insertUserRequest();
            inValue.Body = new WindowsFormsApp2.userServicesReference.insertUserRequestBody();
            inValue.Body.user = user;
            WindowsFormsApp2.userServicesReference.insertUserResponse retVal = ((WindowsFormsApp2.userServicesReference.usersServicesSoap)(this)).insertUser(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp2.userServicesReference.insertUserResponse> WindowsFormsApp2.userServicesReference.usersServicesSoap.insertUserAsync(WindowsFormsApp2.userServicesReference.insertUserRequest request) {
            return base.Channel.insertUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp2.userServicesReference.insertUserResponse> insertUserAsync(WindowsFormsApp2.userServicesReference.UserData user) {
            WindowsFormsApp2.userServicesReference.insertUserRequest inValue = new WindowsFormsApp2.userServicesReference.insertUserRequest();
            inValue.Body = new WindowsFormsApp2.userServicesReference.insertUserRequestBody();
            inValue.Body.user = user;
            return ((WindowsFormsApp2.userServicesReference.usersServicesSoap)(this)).insertUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp2.userServicesReference.GetUserByUsernameResponse WindowsFormsApp2.userServicesReference.usersServicesSoap.GetUserByUsername(WindowsFormsApp2.userServicesReference.GetUserByUsernameRequest request) {
            return base.Channel.GetUserByUsername(request);
        }
        
        public WindowsFormsApp2.userServicesReference.UserData GetUserByUsername(string username) {
            WindowsFormsApp2.userServicesReference.GetUserByUsernameRequest inValue = new WindowsFormsApp2.userServicesReference.GetUserByUsernameRequest();
            inValue.Body = new WindowsFormsApp2.userServicesReference.GetUserByUsernameRequestBody();
            inValue.Body.username = username;
            WindowsFormsApp2.userServicesReference.GetUserByUsernameResponse retVal = ((WindowsFormsApp2.userServicesReference.usersServicesSoap)(this)).GetUserByUsername(inValue);
            return retVal.Body.GetUserByUsernameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp2.userServicesReference.GetUserByUsernameResponse> WindowsFormsApp2.userServicesReference.usersServicesSoap.GetUserByUsernameAsync(WindowsFormsApp2.userServicesReference.GetUserByUsernameRequest request) {
            return base.Channel.GetUserByUsernameAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp2.userServicesReference.GetUserByUsernameResponse> GetUserByUsernameAsync(string username) {
            WindowsFormsApp2.userServicesReference.GetUserByUsernameRequest inValue = new WindowsFormsApp2.userServicesReference.GetUserByUsernameRequest();
            inValue.Body = new WindowsFormsApp2.userServicesReference.GetUserByUsernameRequestBody();
            inValue.Body.username = username;
            return ((WindowsFormsApp2.userServicesReference.usersServicesSoap)(this)).GetUserByUsernameAsync(inValue);
        }
    }
}
